stages:
    - build
    - test 
    - sonarQube

build:
    stage: build
    script:
        - cd Backend
        - ./gradlew build -x test

test:
    stage: test
    script:
        - cd Backend
        - ./gradlew test

sonarQube: 
    stage: sonarQube
    script:
    - ./gradlew sonarqube

